### ISSUE TITLE
Type: number, Format: float becomes a double in C#

### ISSUE THREAD

**Issue by martinmolin** [RicoSuter/NSwag#1122]
According to https://swagger.io/docs/specification/data-models/data-types/

type | format | Description
-- | -- | --
number | – | Any numbers.
number | float | Floating-point numbers.
number | double | Floating-point numbers with double precision.
integer | – | Integer numbers.
integer | int32 | Signed 32-bit integers (commonly used integer type).
integer | int64 | Signed 64-bit integers (long type).

There can be floats as well as doubles, however for the C# generator it seems like both float and double will end up being a double.

**Comment by francesco-scullino** [comment]
Any news?

**Comment by francesco-scullino** [comment]
Any news?

**Comment by RSuter** [comment]
The problem is that float is not handled here: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/DefaultReflectionService.cs#L75

And here: 
https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/CSharpTypeResolver.cs#L140

The format is defined however: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/JsonFormatStrings.cs

**Comment by RSuter** [comment]
BTW: Double and float seem to be not defined format types for JSON Schema: https://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3

**Comment by orihomie** [comment]
There's another problem with float and double and its about this types scopes - they can be Infinity or NaN, but generated json schema points them as "number" only.
I think its could be a problem when casting json types onto C# Dto objects.
