### ISSUE TITLE
Enum with an & generates invalid C#

### ISSUE THREAD

**Issue by MarcusBIM** [RicoSuter/NSwag#1265]
Hi,
I've come across a Swagger file that has an "&" in an enum. which results in invalid c# being created:

`"enum" : [ "Incomplete", "Complete & Awaiting Validation" ]
`
produces:

```
public enum ProcessingStatus
{
    [System.Runtime.Serialization.EnumMember(Value = "Incomplete")]
    Incomplete = 0,
    [System.Runtime.Serialization.EnumMember(Value = "Complete & Awaiting Validation")]
    Complete_&_Awaiting_Validation = 1
}

```

**Comment by RSuter** [comment]
We have to fix this here: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration/DefaultEnumNameGenerator.cs#L22

Or you can provide an own IEnumNameGenerator implementation

**Comment by MarcusBIM** [comment]
Unfortunately, we are currently using the pre-compiled executable to generate our C# code at the moment.

**Comment by DanielSmon** [comment]
Hey there, I'm also having this issue including ampersand (&), hyphen (-), and an apostrophe ('). I've created a PR which adds those characters and changes the colon to convert to an underscore instead of a hyphen: https://github.com/RicoSuter/NJsonSchema/pull/939.

However, I think a better long term solution would be to white-list instead of black-list characters.

**Comment by DanielSmon** [comment]
Just added brackets to the PR as well. Cheers!
