### ISSUE TITLE
jsonschema2csclient creates duplicate objects

### ISSUE THREAD

**Issue by pazoozooCH** [RicoSuter/NSwag#1502]
I'm using jsonschema2csclient to create CS objects from JSON schema. Now I have shared objects that are used in multiple objects, e.g.:

- header.json: Definition of Header
- request1.json: Request1 object with Request1.header from header.json
- request2.json: Request2 object with Request2.header from header.json

Now if I'm running sonschema2csclient twice (creating two files Request1.cs and Request2.cs in the same namespace), both of them will have a definition for Header.

Am I missing something here? Is there a way to create multiple .cs files while respecting shared objects?

My current workaround is to have a dummy all_requests.json referencing request1.json and request2.json. This results in a (big) AllRequests.cs file that has all objects in it. I would prefer individual files for the root objects, though...

**Comment by RSuter** [comment]
1. Each run has its own schema resolver and thus it cannot detect duplicate entries, this is why you get duplicate objects - and this is by design. We could enhance the generator with multiple schema input so that it can do this merge transparently and use the same resolver for both files... (not implemented yet). 
2. NJsonSchema already supports multiple file output, but this is not yet implemented in NSwag - the tooling, CLI, UI, etc. have to be enhanced with this functionality

**Comment by pazoozooCH** [comment]
Thanks for the clarification. I guess I'll live with the workaround for the moment then... :confused:

**Comment by pazoozooCH** [comment]
Wow, 1.8k issues... I'll close this one so it doens't appear in my issues list anymore. Not sure if it's still an issue, but I'm not using `NSwag` anymore...
