### ISSUE TITLE
Is it possible to make Adding Async at the end of a method as Settings option ?

### ISSUE THREAD

**Issue by baskialdensys** [RicoSuter/NSwag#2143]
Thank you for NSwagStudio. If API methods already ends with Async, Code generation adds AsyncAsync at the end. Is it possible to make Adding Async at the end of a method as Settings option ?

**Comment by RicoSuter** [comment]
Why do you have Async in the operationIds in the first place? Aren’t they stripped?

**Comment by baskialdensys** [comment]
We are not setting operationid explicitly. our method looks like below
[HttpGet]
[ProducesResponseType(typeof(List<Company>), 200)]
[ProducesResponseType(typeof(string), 401)]
[ProducesResponseType(typeof(string), 500)]
public async Task<IActionResult> GetCompanyAsync()
{}

**Comment by RicoSuter** [comment]
Are you using Swashbuckle for spec gen (not nswag)?

**Comment by baskialdensys** [comment]
In our asp,net core startup we we use gen
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info
                {
                    Title = "Test Service Web API",
                    Version = "v1",
                    Description = "Test Service for customer management",
                });
            });
then we use the spec from the http://..{}.v1/swagger.json in NswagStudio to create client sdk.

**Comment by RicoSuter** [comment]
First: The spec should not contain Async at all as this is an implementation detail of the backend (i.e. they’re always async). If you’d use NSwag instead of Swashbuckle then these would have been stripped automatically in the spec and the client gen is fine

https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware#register-the-middleware

Second: If the spec contains Async suffixes we should strip them in the client gen first and add then if required - you’ll then end up with only one Async suffix as expected

**Comment by RicoSuter** [comment]
Commit fixes 2.

**Comment by baskialdensys** [comment]
Thank you and appreciate your time. Looking forward to get the next build.

**Comment by RicoSuter** [comment]
Waiting for NJS release: https://ci.appveyor.com/project/rsuter/njsonschema
Then I'll publish a new NSwag version.
