### ISSUE TITLE
AspNetCore Optional Route Parameters not supported?

### ISSUE THREAD

**Issue by MikaelUmaN** [RicoSuter/NSwag#2228]
Hi.

According to: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#route-template-reference

A ? appended to the end of a parameter, as in:

```
        [HttpGet]
        [Route("state/{name?}")]
        public ActionResult<IEnumerable<MonitorState>> GetMonitorState([FromRoute] string name)
```

Should result in an optional parameter. When I create a swagger doc from this using `services.AddSwaggerDocument(...)` the parameter is marked as required, however.

Are optional parameters not supported?

**Comment by RicoSuter** [comment]
Route parameters cannot be optional in OpenAPI/Swagger

**Comment by MikaelUmaN** [comment]
I see, sorry was not aware.

**Comment by look-im-not-your-daddy** [comment]
Mind to share the reason for that? It's a real deal breaker not being able to use optional parameters on an API route because my Swagger generation tool will not support. That influences my product's design.

> Route parameters cannot be optional in OpenAPI/Swagger

Mind to share the reason for that? It's a real deal breaker not being able to use optional parameters on an API route because my Swagger generation tool will not support. That influences my product's design.

**Comment by jeremyVignelles** [comment]
Rico said it was not about the tool, it is about the OpenApi specification.
You can complain there if you want.

**Comment by look-im-not-your-daddy** [comment]
I read some other topics and I understand the mess it is to properly flag an optional segment.

I know I just arrived to the party and for sure I'm oversimplifying things, but I guessing the problem is that the API Explorer returns `required: true` even for a parameter marked with the optional question mark. Is that correct? `/api/users/{id?}`

**Comment by Tri125** [comment]
As I understand it that per the specification it's not possible, but then shouldn't the following example be possible while following the specs:
``
[HttpPut("{id}")]
[HttpPut("{id}/{lang}")]
public async Task<Uri> Update(Guid id, CancellationToken cancellationToken, string lang = null)
{
// my code
}
``

It's two routes, no optional parameters in the route template for a single action. It's very important because we don't want to duplicate the action.
It generate two endpoint in the swagger but then

1. In the API definition UI the endpoint that didn't have the 'lang' in the route have a 'lang' required parameter. This doesn't match the route.

2. The netcore client generator generate two methods: 'Update' and 'Update2' both with nullable 'lang' parameter.

To me that seems to be an odd way to generate from the route information. Personally I would expect the following:

1. Generate two endpoint definition. 1 per route.
2. The endpoint definition without 'lang' in the template shouldn't have a 'lang' parameter.
3. The netcore client generator should generate two methods both named 'Update' one where 'lang' is required, the second where 'lang' is not part of the parameters that you pass to the method.

Wouldn't that respect the OpenAPI definition while simultaneously allowing us to do what we want to do?
