### ISSUE TITLE
How to ignore properties on model if I'm not using Newtonsoft.Json

### ISSUE THREAD

**Issue by hez2010** [RicoSuter/NSwag#2316]
In ASP.NET Core 3.0, Newtonsoft.Json has been removed from Microsoft.AspNetCore.App, so there's no `Newtonsoft.Json.JsonIgnore` by default anymore. Instead, it uses System.Text.Json by default.  

How can I ignore properties on model if I'm not using Newtonsoft.Json? Is there any way to config a custom ignore attribute?

**Comment by RicoSuter** [comment]
Ref: https://github.com/RicoSuter/NSwag/issues/2243

**Comment by dazinator** [comment]
`System.Text.Json` and `Newtonsoft` both have their own ignore attributes. So if you use them, you are coupled with that particular serialiser. No doubt when #2243 is done, you'd opt to use System.Text.Json and then all your generated model classes will have the appropriate attribute rather than newtonsofts.

However Newtonsoft also honours DataContract's i.e `System.Runtime.Serialisation` attributes - which is awesome as DataContracts are a way that models can opt properties into serialisation in a way that doesn't couple them with a particular serialiser. However microsoft have no plans to extend `System.Text.Json` to support `System.Runtime.Serialisation` data contract attributes - which imho is crazy.  https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonignoreattribute?view=netcore-3.0

If Microsoft did do that, it would be possible for tools like NSwag to generate less serialiser specific code, as models could use data contracts.

**Comment by eldortemirov** [comment]
How about the attribute BindNeverAttribute from assembly Microsoft.AspNetCore.Mvc.Core?  [BindNever] ignores the properties on the model. Give it a try!

**Comment by RicoSuter** [comment]
We probably need to set the property to ignored when the System.Text.Json ignore attribute is on the property: 

https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/SystemTextJsonUtilities.cs#L56
