### ISSUE TITLE
Swagger UI empty Path

### ISSUE THREAD

**Issue by meareindel** [RicoSuter/NSwag#2510]
I want to publish swagger ui on my application root (it is aggregated swagger with several swagger routers). So I do this in Startup:

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, IConfiguration configuration)
        {
            app.UseSwaggerUi3(options =>
               {
                   options.Path = "";
               });
        }

But when I go for root in browser (eg. http://localhost:5000/) it redirects to http://index.html.

Is it supported scenario (bug in other words), or maybe I'm doing it wrong?

NSwag last release.

**Comment by RicoSuter** [comment]
Have you tried `options.Path = "/";`?

I've never tried to render it in the root.

**Comment by meareindel** [comment]
I've tried it first, but it says System.ArgumentException: 'Request path must not end in a slash'

**Comment by PhillipChaffee** [comment]
I have this same issue. Looking into fixing it now.

**Comment by PhillipChaffee** [comment]
Fixed this and tested locally. @RicoSuter let me know if you have any questions.

**Comment by changhuixu** [comment]
In Swashbuckle, this is a feature can be achieved by setting Path to `string.Empty`. Please read this part of documentation ([link](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.0&tabs=visual-studio#add-and-configure-swagger-middleware))

I'd prefer to see a bool or a string.Empty parameter, instead of "/", which is a magic string.
@PhillipChaffee and @RicoSuter , could you please review the ffix by @PhillipChaffee ?

This feature is useful for some API only websites.

Thank you.

**Comment by RicoSuter** [comment]
Can you create a PR?

**Comment by changhuixu** [comment]
Hi @RicoSuter , I have checked the latest merged master branch, and I don't think I need to do extra.
I have submitted a very small pull request with my findings in the commit message. You can take a look and you might want to document it somewhere. 
And I think you can close this issue when you release a new version.
Thanks a lot.

**Comment by RicoSuter** [comment]
PR merged - closing issue...
