### ISSUE TITLE
Question on OpenAPI 3.0.3

### ISSUE THREAD

**Issue by niraj-bits** [RicoSuter/NSwag#3097]
My apologies if this is a stupid question. The OAS 3.0.3 was released in Feb, see [here](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.3).

The changes were made to improve the specification in terms of readability and accuracy. None of these modifications change the behavior of the spec and I take it that NSwag isn't affected and fully supports 3.0.3.

It will be nice to get confirmation from others, preferably the author himself.

**Comment by RicoSuter** [comment]
Yes, i would agree that from the view of NSwag this should not have any impact, i.e. the spec generator might not use all new features but the generated spec is still valid - but some new features might not be supported by the client generator... (but it seems 3.0.3 does not add new spec features, just updated docs).

**Comment by bbarry** [comment]
I don't think it generates a 3.0.3 document yet though ([still 3.0.0 I believe due to this](https://github.com/RicoSuter/NSwag/blob/85ae862fd6d68173a201a79e0ad06e0be2ec5de1/src/NSwag.Core/OpenApiDocument.cs#L31)) so any PRs that use new semantics causing it to generate a document not compatible with 3.0.0 would require that field to be updated right? I don't think there are any such changes in the spec until OAS 3.1 comes out (it is currently [rc0](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0))

**Comment by niraj-bits** [comment]
Thank you Rico and barry for the quick response.

**Comment by RicoSuter** [comment]
> I don't think it generates a 3.0.3 document yet though

That's correct - in theory we could just change that to 3.0.3, but i dont think this makes a difference, no?

**Comment by bbarry** [comment]
For 3.0.0 I think it is probably wrong to update that field to 3.0.3 unless it was required due to some commit that made the document no longer compatible with 3.0.0 (assuming any defects that cause an invalid document per spec are not applicable). 

For 3.1 reading the RC spec I think it would be appropriate to use whichever is the current one being adhered to because they state they are no longer following semver. I think that is hard to say though without knowing what is in 3.1.1 or later because 3.1 might just be not following semver due to the breaking changes from 3.0 and not due to plans to have breaking changes in point releases.
