### ISSUE TITLE
TS Client Generation: IAsyncEnumerable<Foo> is generated as Anonymous[]

### ISSUE THREAD

**Issue by cypressious** [RicoSuter/NSwag#3332]
I have a Controller method with the signature

```cs
[HttpPost("{machineId}/measurements/import")]
[Authorize(Policy = AuthExtensions.PolicyStaff)]
public async IAsyncEnumerable<ImportResultModel> ImportMeasurements(
    string machineId,
    IEnumerable<IFormFile> files,
    [FromServices] MeasurementsExcelImport import)
```

Before I updated NSwag from 13.10.1 to 13.10.6, the TS client was generated as

```ts
importMeasurements(machineId: string, files: FileParameter[] | undefined): Promise<ImportResultModel[]>
```

whereas now it's generated as

```ts
importMeasurements(machineId: string, files: FileParameter[] | undefined): Promise<Anonymous[]>
```

**Comment by RicoSuter** [comment]
Working versions:

- NSwag: 13.10.1
- NJS: 10.3.3

@jeremyVignelles could this be a problem with our changes in Namotion.Reflection? I see we switched to the improved version in NJS 10.3.4

**Comment by RicoSuter** [comment]
Yep we definitely broke this with the PR
https://github.com/RicoSuter/Namotion.Reflection/pull/59

![image](https://user-images.githubusercontent.com/2603405/109290333-c2ab5c80-7827-11eb-8294-f877f7333eb2.png)

**Comment by jeremyVignelles** [comment]
@RicoSuter : We had a discussion about the IAsyncEnumerable in the context of Model serialization/deserialization, which I found useless ((de)serialization is always synchronous).

Now, the return value of a method, that's another story...

From the Namotion.Reflection perspective, should `EnumerableItemType` detect the type of `IAsyncEnumerable<T>` ? It's not directly enumerable, since that's an async enumerable...
Should it be handled in Namotion.Reflection?

**Comment by RicoSuter** [comment]
> We had a discussion about the IAsyncEnumerable in the context of Model serialization/deserialization, which I found useless ((de)serialization is always synchronous).

Ah yes, we didnt think about the operation return type case where it actually makes sense and where JSON Schema generation as actually also used.
