### ISSUE TITLE
 Fluid.ParseException: '{% endif %}' was expected at (25:1) on client.class

### ISSUE THREAD

**Issue by Anderman** [RicoSuter/NSwag#3808]
When upgrading from 13.14.8 to 13.15.x an error is thrown when gegenerate charp class
 Fluid.ParseException: '{% endif %}' was expected at (25:1)

  System.InvalidOperationException: Error while rendering Liquid template CSharp/Client.Class:
  Fluid.ParseException: '{% endif %}' was expected at (25:1)

this line on src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid
`public {{ Class }}(string baseUrl{% if InjectHttpClient %}, {{ HttpClientType }} httpClient{% endif %})`
is missing a `-`
`public {{ Class }}(string baseUrl{% if InjectHttpClient %}, {{ HttpClientType }} httpClient{%- endif %})`

**Comment by lahma** [comment]
> Is this your custom template or one shipped with NSwag? This error usually means template has used `elseif` instead of correct `elsif` .

**Comment by Anderman** [comment]
We not using own templates for the c# client

**Comment by lahma** [comment]
Can you check all the packages are up to date, including NJsonSchema. There are a lot of test generating C# client (I'm also using the lib to generate), they would fail on invalid template as all templates are being parser before use.

**Comment by danlbb** [comment]
I experienced this exact problem after upgrading to 13.15.5, albeit using NSwag from a nuget package. I ended up copying the Net60 tool from the NSwag.MSBuild nuget to see the errors more clearly, rather than just getting an "exited with code -1" in Visual Studio.

I didn't uncover the cause, but I downgraded to 13.14.5 and it's working again. I am using custom templates, but even without them it wouldn't work on the new version.

To give you some to go from, however, it would seem that it's related to some of the dependencies shipped with nswag.msbuild:13.15.5.

**Comment by danlbb** [comment]
> @danlbb do your custom templates have `elseif` in them?

Ah, yes, that's the issue exactly. Apologies for missing your answer - I was looking in my Class.liquid file instead of my **Client**.Class.liquid file :)

I can see you fixed it on December 2nd: https://github.com/RicoSuter/NSwag/commit/87d7ca7ba79d939ecc7977f36953249980e1f57a
