### ISSUE TITLE
Moving from Swashbuckle.AspNetCore to NSwag

### ISSUE THREAD

**Issue by codelovercc** [RicoSuter/NSwag#4652]
Thank you for your job! Since [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) has not seen a commit in 11 months, it's maybe out of support(I don't know). There're many people are planing to move to NSwag. Do we have a guidance for this or could you provide one? guidance for Swashbuckle.AspNetCore filter/configuration etc..

**Comment by SerhiyBalan** [comment]
@codelovercc  This is a great project. I've easily migrated to it since it requires less extra coding compared to Swashbuckle

But it has its own issues. The most important for me is that it is linked strictly to the .NET framework version. I have to use a v14.0 preview version for more than one month https://github.com/RicoSuter/NSwag/issues/4583
And looks like it happens each year with a new .NET release.

As for migration, use this article to find out how to set most common stuff: https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag

**Comment by EffivityPK** [comment]
How did you handle Models that have BsonDocument tye in them?

**Comment by PsyhoLord** [comment]
[Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) has update to version 6.6.X that already supports .Net8, so welcome
