### ISSUE TITLE
Update middleware wiki

### ISSUE THREAD

**Issue by RicoSuter** [RicoSuter/NSwag#480]
@RobertDyball Maybe we should update the wiki for the middlewares based on your findings?

https://github.com/NSwag/NSwag/wiki/Middlewares

What changes to the documentation are needed?
What could be improved with the tooling so that the integration is simpler?

**Comment by RobertDyball** [comment]
still a little early to comment with anything too concrete, spent much of today through a few other issues on a larger site.
 
The simple Owin website I knocked up and added to the repo works well enough, even the standard basic authentication version fine. Using the fileserver fix, to serve static files seems to have a side effect on that larger site I am working on, where the site loses cache headers and 302 redirect from the login page is ignored. I can't replicate yet on a smaller scale, to narrow down the issue. Will have to wait until Monday my time now. 

NSwag seems to sit heavily in the site, as it is, and routing doesn't seem limited to /swagger, but something is amiss that causes it to need to have special explicit handling of the static files. This site uses an ASP.Net MVC 4.5x backend and SPA pages using static HTML through an Angular JS 1.5x front end.

Apps such as hangfire don't seem to affect static files or other routes, so perhaps this is an area that could benefit from some work.

Again I'll try and see what I can find and get back to you next week.

**Comment by RobertDyball** [comment]
Found the issues stemmed from moving Web API to Microsoft.AspNet.WebApi.Owin , as this meant serialization defaulted back to Pascal Case instead of Camel Case, the Camel Case settings that previously operated on Web API didn't work with the Owin version. The rest of the existing site (still using static file fix) works, including Hangfire and Signal-R.

Next issue I need to tackle is apparent multiple similar methods; proving difficult to find why I get multiple get's to say api/users or the like. Might be nice to have an option to  methodAddOperationDescriptionsToDocument in class WebApiToSwaggerGenerator to allow ignoring second / subsequent duplicates (or add more detail to help find them).

something like:

    var addOperation = RunOperationProcessors(document, method, operation, allOperation, swaggerGenerator);
    if (addOperation)
    {
        if (!document.Paths.ContainsKey(operation.Path))
        {
            document.Paths[operation.Path] = new SwaggerOperations();
        }
        else
        {
            if (document.Paths[operation.Path].ContainsKey(operation.Method))
            {
                if (skipDuplicates)
                    break;

                throw new InvalidOperationException("The method '" + operation.Method + "' on path '" + operation.Path + "' is registered multiple times.");
                }

                document.Paths[operation.Path][operation.Method] = operation.Operation;
        }

Hope to complete the rest using [SwaggerIgnore] Swagger Ignore attribute, and then add some security in front of the whole thing.

**Comment by rsuter** [comment]
Maybe you have to change the DefaultUrlTemplate, by default it does not contain {action}

**Comment by RSuter** [comment]
Just FYI: The wiki can now be improved by everyone...
