### ISSUE TITLE
Better Extensibility

### ISSUE THREAD

**Issue by Cephei** [RicoSuter/NSwag#624]
Please consider adding more extensibility points:
- program to interfaces/abstractions (e.g. SwaggerGenerator.cs)
- protected virtual methods instead of private (where applicable)

**Comment by rsuter** [comment]
In general this is a good idea... but I want to keep the API as small as possible to avoid breaking changes in the future... I also think that SwaggerGenerator is not stable yet because it is only used for Web API processing. This generator is meant to be used for other frameworks (e.g. Nancy) and provides helper methods to generate Swagger specs. I think opening it up makes only sense when we know that it contains all shareable logic and how it would be extended... 

Do you have specific needs for extension points?

**Comment by RicoSuter** [comment]
Closing as too old and many extension points have been added.
